services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_DATABASE: mvps-dev-db
      MYSQL_USER: mvps-dev-db-user
      MYSQL_PASSWORD: mvps-dev-db-pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    working_dir: /app/app
    volumes:
      - .:/app
    env_file:
      - app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - redis
      - web
      - db
  

  celery-beat:
    build: .
    command: celery -A config beat --loglevel=info
    working_dir: /app/app
    volumes:
      - .:/app
    env_file:
      - app/.env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    depends_on:
      - redis
      - web
      - db

volumes:
  db_data:
