# Generated by Django 5.2.4 on 2025-07-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangeratelog',
            unique_together=set(),
        ),
    ]
