# Generated by Django 5.2.4 on 2025-07-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_exchangeratelog_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeratelog',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.RenameField(
            model_name='exchangeratelog',
            old_name='date',
            new_name='fetched_at',
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=15),
        ),
    ]
